"""塔罗牌数据：78 张莱德-伟特（RWS）牌面基础信息。

牌名与传统关键词属公共领域；卡面图片为 1909 年 Pamela Colman Smith 原版扫描
（Wikimedia Commons，公有领域），见 static/tarot/cNN.jpg。
本文件由构建脚本从提取数据生成，请勿手改。"""

CARDS = [
    dict(n=1, name="愚者", en="The Fool",
         arcana="major", up=("新的开始", "冒险", "纯真", "无限可能"), rev=("鲁莽", "犹豫不决", "缺乏方向")),
    dict(n=2, name="魔术师", en="The Magician",
         arcana="major", up=("创造力", "意志力", "技能", "资源齐备"), rev=("欺骗", "操纵", "才华浪费")),
    dict(n=3, name="女祭司", en="The High Priestess",
         arcana="major", up=("直觉", "潜意识", "神秘", "静观其变"), rev=("秘密泄露", "忽视直觉", "流于表面")),
    dict(n=4, name="皇后", en="The Empress",
         arcana="major", up=("丰饶", "滋养", "创造力", "母性"), rev=("依赖", "停滞", "创造受阻")),
    dict(n=5, name="皇帝", en="The Emperor",
         arcana="major", up=("权威", "秩序", "稳定", "领导力"), rev=("专横", "僵化", "失控")),
    dict(n=6, name="教皇", en="The Hierophant",
         arcana="major", up=("传统", "信仰", "教诲", "制度"), rev=("叛逆", "打破常规", "质疑权威")),
    dict(n=7, name="恋人", en="The Lovers",
         arcana="major", up=("爱情", "结合", "选择", "价值观"), rev=("不和", "错位", "摇摆不定")),
    dict(n=8, name="战车", en="The Chariot",
         arcana="major", up=("胜利", "意志", "前进", "掌控"), rev=("失控", "受阻", "方向迷失")),
    dict(n=9, name="力量", en="Strength",
         arcana="major", up=("勇气", "耐心", "内在力量", "温柔"), rev=("自我怀疑", "软弱", "压抑")),
    dict(n=10, name="隐士", en="The Hermit",
         arcana="major", up=("内省", "独处", "寻求真理", "智慧"), rev=("孤立", "逃避", "固执己见")),
    dict(n=11, name="命运之轮", en="Wheel of Fortune",
         arcana="major", up=("转机", "命运", "周期", "好运"), rev=("厄运", "抗拒变化", "停滞")),
    dict(n=12, name="正义", en="Justice",
         arcana="major", up=("公正", "因果", "平衡", "真相"), rev=("不公", "失衡", "逃避责任")),
    dict(n=13, name="倒吊人", en="The Hanged Man",
         arcana="major", up=("换位思考", "牺牲", "暂停", "顿悟"), rev=("拖延", "无谓牺牲", "僵持")),
    dict(n=14, name="死神", en="Death",
         arcana="major", up=("结束", "蜕变", "放下", "新生"), rev=("抗拒改变", "停滞", "恐惧告别")),
    dict(n=15, name="节制", en="Temperance",
         arcana="major", up=("平衡", "调和", "耐心", "适度"), rev=("失衡", "过度", "失调")),
    dict(n=16, name="恶魔", en="The Devil",
         arcana="major", up=("束缚", "诱惑", "执念", "欲望"), rev=("挣脱", "觉醒", "戒断")),
    dict(n=17, name="高塔", en="The Tower",
         arcana="major", up=("剧变", "崩塌", "真相", "解放"), rev=("侥幸", "恐惧剧变", "延迟")),
    dict(n=18, name="星星", en="The Star",
         arcana="major", up=("希望", "疗愈", "灵感", "宁静"), rev=("失望", "失去信心", "悲观")),
    dict(n=19, name="月亮", en="The Moon",
         arcana="major", up=("幻象", "不安", "直觉", "潜意识"), rev=("迷雾散去", "真相浮现", "释然")),
    dict(n=20, name="太阳", en="The Sun",
         arcana="major", up=("成功", "喜悦", "活力", "光明"), rev=("延迟的快乐", "过度乐观", "小挫")),
    dict(n=21, name="审判", en="Judgement",
         arcana="major", up=("觉醒", "召唤", "复盘", "重生"), rev=("自我批判", "逃避", "停滞")),
    dict(n=22, name="世界", en="The World",
         arcana="major", up=("完成", "圆满", "成就", "整合"), rev=("未竟", "拖延", "缺憾")),
    dict(n=23, name="权杖王牌", en="Ace of Wands",
         arcana="minor", up=("新机会", "创造力火花", "热情开端"), rev=("延迟", "缺乏热情", "灵感枯竭")),
    dict(n=24, name="权杖二", en="Two of Wands",
         arcana="minor", up=("规划", "远见", "掌控全局"), rev=("恐惧未知", "犹豫", "格局受限")),
    dict(n=25, name="权杖三", en="Three of Wands",
         arcana="minor", up=("展望", "扩张", "远航"), rev=("延误", "视野受限", "合作受阻")),
    dict(n=26, name="权杖四", en="Four of Wands",
         arcana="minor", up=("庆祝", "和谐", "家园", "里程碑"), rev=("根基不稳", "缺乏归属", "庆祝推迟")),
    dict(n=27, name="权杖五", en="Five of Wands",
         arcana="minor", up=("竞争", "冲突", "较量"), rev=("和解", "避免冲突", "合作")),
    dict(n=28, name="权杖六", en="Six of Wands",
         arcana="minor", up=("胜利", "认可", "凯旋"), rev=("失败", "荣誉迟来", "自我怀疑")),
    dict(n=29, name="权杖七", en="Seven of Wands",
         arcana="minor", up=("坚守", "防御", "立场"), rev=("放弃", "疲惫", "寡不敌众")),
    dict(n=30, name="权杖八", en="Eight of Wands",
         arcana="minor", up=("快速进展", "消息", "行动"), rev=("延误", "停滞", "急躁")),
    dict(n=31, name="权杖九", en="Nine of Wands",
         arcana="minor", up=("坚韧", "警觉", "最后防线"), rev=("疲惫", "防备过度", "放弃")),
    dict(n=32, name="权杖十", en="Ten of Wands",
         arcana="minor", up=("重担", "责任", "劳累"), rev=("卸担", "逃避责任", "过度承担")),
    dict(n=33, name="权杖侍从", en="Page of Wands",
         arcana="minor", up=("探索", "热情", "新消息"), rev=("三分钟热度", "鲁莽", "消息延误")),
    dict(n=34, name="权杖骑士", en="Knight of Wands",
         arcana="minor", up=("冒险", "行动", "冲动"), rev=("鲁莽", "半途而废", "急躁")),
    dict(n=35, name="权杖女王", en="Queen of Wands",
         arcana="minor", up=("自信", "魅力", "热情"), rev=("嫉妒", "专横", "外强中干")),
    dict(n=36, name="权杖国王", en="King of Wands",
         arcana="minor", up=("领袖", "远见", "创业精神"), rev=("专断", "急躁", "刚愎自用")),
    dict(n=37, name="圣杯王牌", en="Ace of Cups",
         arcana="minor", up=("爱", "情感满溢", "新感情"), rev=("情感闭塞", "空虚", "压抑")),
    dict(n=38, name="圣杯二", en="Two of Cups",
         arcana="minor", up=("联结", "互信", "恋情"), rev=("失衡", "疏离", "误解")),
    dict(n=39, name="圣杯三", en="Three of Cups",
         arcana="minor", up=("友谊", "庆祝", "团体"), rev=("孤立", "流言", "过度放纵")),
    dict(n=40, name="圣杯四", en="Four of Cups",
         arcana="minor", up=("倦怠", "不满", "沉思"), rev=("新机会", "醒悟", "重新投入")),
    dict(n=41, name="圣杯五", en="Five of Cups",
         arcana="minor", up=("失落", "遗憾", "悲伤"), rev=("释怀", "走出阴霾", "接纳")),
    dict(n=42, name="圣杯六", en="Six of Cups",
         arcana="minor", up=("怀旧", "纯真", "旧识重逢"), rev=("沉溺过去", "停滞", "长不大")),
    dict(n=43, name="圣杯七", en="Seven of Cups",
         arcana="minor", up=("选择", "幻象", "想象"), rev=("清醒", "落地", "做决定")),
    dict(n=44, name="圣杯八", en="Eight of Cups",
         arcana="minor", up=("离开", "寻找", "放手"), rev=("回头", "害怕改变", "徘徊")),
    dict(n=45, name="圣杯九", en="Nine of Cups",
         arcana="minor", up=("满足", "如愿", "享受"), rev=("贪心", "不满足", "虚荣")),
    dict(n=46, name="圣杯十", en="Ten of Cups",
         arcana="minor", up=("幸福", "圆满家庭", "和谐"), rev=("破碎", "失落", "家庭矛盾")),
    dict(n=47, name="圣杯侍从", en="Page of Cups",
         arcana="minor", up=("灵感", "情感消息", "温柔"), rev=("情绪化", "幼稚", "不靠谱")),
    dict(n=48, name="圣杯骑士", en="Knight of Cups",
         arcana="minor", up=("浪漫", "追求", "邀请"), rev=("情绪波动", "不靠谱", "空头支票")),
    dict(n=49, name="圣杯女王", en="Queen of Cups",
         arcana="minor", up=("共情", "直觉", "关怀"), rev=("过度敏感", "依赖", "情绪淹没")),
    dict(n=50, name="圣杯国王", en="King of Cups",
         arcana="minor", up=("成熟", "情绪稳定", "慈悲"), rev=("压抑情感", "冷漠", "情绪操纵")),
    dict(n=51, name="宝剑王牌", en="Ace of Swords",
         arcana="minor", up=("真相", "清晰", "突破"), rev=("混乱", "误解", "鲁莽")),
    dict(n=52, name="宝剑二", en="Two of Swords",
         arcana="minor", up=("僵局", "逃避选择", "平衡"), rev=("决断", "真相大白", "打破僵局")),
    dict(n=53, name="宝剑三", en="Three of Swords",
         arcana="minor", up=("心痛", "悲伤", "真相刺痛"), rev=("疗愈", "释怀", "原谅")),
    dict(n=54, name="宝剑四", en="Four of Swords",
         arcana="minor", up=("休息", "疗养", "暂停"), rev=("倦怠", "恢复期躁动", "提前行动")),
    dict(n=55, name="宝剑五", en="Five of Swords",
         arcana="minor", up=("冲突获胜却空虚", "好胜", "不光彩"), rev=("和解", "放下争执", "止损")),
    dict(n=56, name="宝剑六", en="Six of Swords",
         arcana="minor", up=("过渡", "疗愈之旅", "远离纷扰"), rev=("困在原地", "逃避", "停滞")),
    dict(n=57, name="宝剑七", en="Seven of Swords",
         arcana="minor", up=("策略", "隐瞒", "独行"), rev=("坦诚", "坦白", "被识破")),
    dict(n=58, name="宝剑八", en="Eight of Swords",
         arcana="minor", up=("束缚", "自我设限", "无力"), rev=("解放", "突破", "看清出口")),
    dict(n=59, name="宝剑九", en="Nine of Swords",
         arcana="minor", up=("焦虑", "噩梦", "担忧"), rev=("释然", "放下忧虑", "寻求帮助")),
    dict(n=60, name="宝剑十", en="Ten of Swords",
         arcana="minor", up=("终结", "低谷", "最坏已过"), rev=("复苏", "浴火重生", "慢慢恢复")),
    dict(n=61, name="宝剑侍从", en="Page of Swords",
         arcana="minor", up=("警觉", "好奇", "新消息"), rev=("多疑", "口舌", "消息失真")),
    dict(n=62, name="宝剑骑士", en="Knight of Swords",
         arcana="minor", up=("冲刺", "激进", "争辩"), rev=("鲁莽", "失控", "言语伤人")),
    dict(n=63, name="宝剑女王", en="Queen of Swords",
         arcana="minor", up=("独立", "清醒", "理性"), rev=("尖刻", "冷酷", "愤世嫉俗")),
    dict(n=64, name="宝剑国王", en="King of Swords",
         arcana="minor", up=("理性", "公正", "权威"), rev=("专横", "冷酷", "滥用权力")),
    dict(n=65, name="星币王牌", en="Ace of Pentacles",
         arcana="minor", up=("财富", "机遇", "实际开端"), rev=("浪费", "错失", "财务不稳")),
    dict(n=66, name="星币二", en="Two of Pentacles",
         arcana="minor", up=("平衡收支", "灵活", "多任务"), rev=("失衡", "混乱", "应接不暇")),
    dict(n=67, name="星币三", en="Three of Pentacles",
         arcana="minor", up=("协作", "技艺", "团队"), rev=("低质", "不合作", "独木难支")),
    dict(n=68, name="星币四", en="Four of Pentacles",
         arcana="minor", up=("稳固", "储蓄", "保守"), rev=("吝啬", "僵化", "抓太紧")),
    dict(n=69, name="星币五", en="Five of Pentacles",
         arcana="minor", up=("匮乏", "困境", "孤立"), rev=("转机", "援助", "走出低谷")),
    dict(n=70, name="星币六", en="Six of Pentacles",
         arcana="minor", up=("给予", "互助", "慷慨"), rev=("索取", "不平等", "施舍")),
    dict(n=71, name="星币七", en="Seven of Pentacles",
         arcana="minor", up=("耕耘", "评估", "耐心"), rev=("失望", "放弃", "急于求成")),
    dict(n=72, name="星币八", en="Eight of Pentacles",
         arcana="minor", up=("精进", "专注", "学徒"), rev=("敷衍", "分心", "粗制滥造")),
    dict(n=73, name="星币九", en="Nine of Pentacles",
         arcana="minor", up=("自律", "独立", "丰裕"), rev=("孤立", "过度工作", "失去享受")),
    dict(n=74, name="星币十", en="Ten of Pentacles",
         arcana="minor", up=("传承", "家族", "长久富足"), rev=("纷争", "家业不稳", "断代")),
    dict(n=75, name="星币侍从", en="Page of Pentacles",
         arcana="minor", up=("学习", "新技能", "务实"), rev=("拖延", "不踏实", "空想")),
    dict(n=76, name="星币骑士", en="Knight of Pentacles",
         arcana="minor", up=("勤奋", "可靠", "稳步"), rev=("停滞", "懒散", "一成不变")),
    dict(n=77, name="星币女王", en="Queen of Pentacles",
         arcana="minor", up=("务实", "滋养", "富足"), rev=("操心过度", "物质化", "忽略自我")),
    dict(n=78, name="星币国王", en="King of Pentacles",
         arcana="minor", up=("成功", "稳健", "理财"), rev=("贪婪", "固执", "物质至上")),
]
